/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "Ifx_Cfg.h"
#include "IfxCpu.h"
#include "IfxWtu.h"
#include "serialio.h"
#include "mtp_application.h"

void UART_Get_Char(uint8_t character);

#define UART_BAUDRATE           115200

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

/*
 * Configuration of UART pin and module for TC375 Lite Kit
 */
SERIALIO_t SERIALIO =
{
  .asclin = &MODULE_ASCLIN0,
  .tx_pin = &IfxAsclin0_TX_F_P14_0_OUT,
  .rx_pin = &IfxAsclin0_RXA_F_P14_1_IN
};


void UART_Get_Char(uint8_t character)
{
    static uint8_t char_idx = 0;
    static char strings[16] = {0};

    strings[char_idx] = character;


#if 0

    if (strings[char_idx] == ':')
            {
                char_idx = 0; // ignoring the bytes upto ':'. in the test case string "Tc:num;", we are only interested in the "num;" part
            }
            else if (strings[char_idx] == ';')
            {
                strings[char_idx] = '\0';
                char_idx = 0;
                sscanf(strings, "%d\n\r", (int *)&current_test); // converting the received number in str format to integer format
                // Term_Printf(" ins: Test case : %d\n\r",(uint8_t)current_test);
                new_test = true; // new test case is detected
            }
            else if (strings[0] == '\r')
            {
                if (new_test)
                    start_test = true; // start the test only if new_test is detected.
                                       // If the start button in GUI is randomly pressed without going to a new test case, it will not trigger the test .
            }
            else if (strings[0] == '\x03')
            {
                if (new_test && !start_test) // skip the test, once a new test is detected and not started. Cant skip a test which has already started.
                    skip_test = true;
            }
            else if (strings[0] == 'p')
            {
                if (new_test && start_test) // pass or fail a test only after it had started. Cant pass/fail a test before starting it
                    test_passed = true;
            }
            else if (strings[0] == 'f')
            {
                if (new_test && start_test)
                    test_failed = true;
            }
            else
            {
                char_idx++; // increment and receive the next byte
            }
#endif




    if((strings[char_idx] == '\x03')||(strings[char_idx] == 'p')||(strings[char_idx] == 'f')||(strings[char_idx] == '\r')||(strings[char_idx] == ';'))
        char_idx = 0;
    else
        char_idx++;

}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());
    
    //IfxCpu_emitEvent(&g_cpuSyncEvent);
    //IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    SERIALIO_Init(UART_BAUDRATE);


    printf("\n\r");
    printf("************************************\n\r");
    printf("*         TC375 Lite Kit           *\n\r");
    printf("*          Serial Printf           *\n\r");
    printf("* Date: %10s                *\n\r", __DATE__);
    printf("************************************\n\r");

    while (1)
    {
    }
}
