/**********************************************************************************************************************
 * \file Flash_Programming.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <string.h>
#include "Ifx_Types.h"
#include "Flash_Programming.h"
#include "IfxFlash.h"
#include "IfxCpu.h"
#include "IfxPort.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define FLASH_MODULE                0                           /* Macro to select the flash (PMU) module           */

#define TEST_PASS                   0xAAAAAAAA
#define TEST_FAIL                   0x55555555

#define SUCCESS                     (1u)
#define FAILURE                     (0u)

#define DFLASH_STARTING_ADDRESS     0xAE000000                  /* Address of the DFLASH where the data is written  */

#define DFLASH_SINGLE_SECTORS       1 // 1 sector = 2048 page    /* Number of DFLASH sectors to be erased            */
#define DFLASH_ERASE_SECTOR_SIZE    (2048)

#define MEM(address)                *((uint32 *)(address))      /* Macro to simplify the access to a memory address */



/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


void writeStatusToFlash(uint8 testID, boolean status)
{
    uint32 Data = 0;

    /* Reset the addressed command sequence interpreter */
    IfxFlash_resetToRead(FLASH_MODULE);
    /* Clear flags */
    IfxFlash_clearStatus(FLASH_MODULE);



    /* --------------- ERASE PROCESS --------------- */
    uint32 EraseAddress = (DFLASH_STARTING_ADDRESS + (testID * DFLASH_ERASE_SECTOR_SIZE));
    /* Erase the sector */
    IfxFlash_eraseMultipleSectors(EraseAddress, DFLASH_SINGLE_SECTORS); /* Erase the given sector           */
    /* Wait until request is executed */
    while(FALSE == IfxFlash_isRequestExecuted()) {}
    /* Clear flags */
    IfxFlash_clearStatus(FLASH_MODULE);



    /* --------------- WRITE PROCESS --------------- */

    if(status == SUCCESS)
    {
        Data = TEST_PASS;
    }
    else if(status == FAILURE)
    {
        Data = TEST_FAIL;
    }

    uint32 pageAddr = DFLASH_STARTING_ADDRESS + (testID * DFLASH_ERASE_SECTOR_SIZE); /* Get the address of the page     */
    /* Enter in page mode */
    IfxFlash_enterPageMode(pageAddr);
    /* Wait until page mode is entered */
    while(FALSE == IfxFlash_isDflashInPageMode()) {}
    /* Clear flags */
    IfxFlash_clearStatus(FLASH_MODULE);
    /* Load data to be written in the page */
    IfxFlash_loadPage2X32(pageAddr, Data, Data); /* Load two words of 32 bits each            */
    /* Clear flags */
    IfxFlash_clearStatus(FLASH_MODULE);
    /* Write the loaded page */
    IfxFlash_writePage(pageAddr);                           /* Write the page                                   */
    /* Wait until request is executed */
    while(FALSE == IfxFlash_isRequestExecuted()) {}
    /* Clear flags */
    IfxFlash_clearStatus(FLASH_MODULE);
}

uint32 Mem_Val = 0;

/* This function verifies if the data has been correctly written in the Data Flash */
boolean readStatusFromFlash(uint8 testID)
{

    uint32 pageAddr = DFLASH_STARTING_ADDRESS + (testID * DFLASH_ERASE_SECTOR_SIZE);    /* Get the address of the page  */

    /* Check if the data in the Data Flash is correct */
    Mem_Val = (MEM(pageAddr));

    if(MEM(pageAddr) == TEST_PASS)
    {
        return TRUE;
    }
    else if(MEM(pageAddr) == TEST_FAIL)
    {
        return FALSE;
    }
    else
    {
        return FALSE;
    }

}



