/**********************************************************************************************************************
 * \file EGTM_ATOM_Interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <stdio.h>
#include "IfxEgtm_Atom_Timer.h"
#include "mtp_application.h"
#include "IfxAsclin_bf.h"
#include "IfxAsclin_bf.h"
#include "IfxAsclin_Asc.h"
#include "Asclin/Std/IfxAsclin.h"





/*********************************************************************************************************************/
/*                                                          Main                                                     */
/*********************************************************************************************************************/








/*********************************************************************************************************************/
/*                                                       UART                                                        */
/*********************************************************************************************************************/

#define SERIALIO_STRLEN         1024
#define UART_BAUDRATE           115200
#define UART_INT_PRIO_RX        (4)

#define PRINT_STRING( x )    fprintf(stderr, x)
#define PRINTF_STRING(...) { do {sprintf(SERIALIO.str, __VA_ARGS__); PRINT_STRING(SERIALIO.str);} while(0);}


typedef struct SERIALIO
{
    Ifx_ASCLIN *const asclin;
    IfxAsclin_Tx_Out *const tx_pin;
    IfxAsclin_Rx_In *const rx_pin;
    char str[SERIALIO_STRLEN];
} SERIALIO_t;

// Configuration of UART pin and module for TC4D7 Lite Kit
SERIALIO_t SERIALIO =
{
  .asclin = &MODULE_ASCLIN0,
  .tx_pin = &IfxAsclin0_TX_F_P14_0_OUT,
  .rx_pin = &IfxAsclin0_RXA_F_P14_1_IN
};

/* Create an instance of the ASC handle */
static IfxAsclin_Asc ascHandle;


IFX_INTERRUPT(uartRxIsr, 0, UART_INT_PRIO_RX);
void uartRxIsr(void)
{
    uint8 ascData;
    uint8 count;

    count = IfxAsclin_getRxFifoFillLevel(ascHandle.asclin);

    while(count > 0)
    {
        IfxAsclin_read8(ascHandle.asclin, &ascData, 1);
        UART_Get_Char(ascData);
        count--;
    }
}


void SERIALIO_Init(void)
{

    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, SERIALIO.asclin);

    ascConfig.baudrate.baudrate = (float32)UART_BAUDRATE;                            /* Set the desired baud rate         */
    ascConfig.baudrate.oversampling         = IfxAsclin_OversamplingFactor_16;
    ascConfig.bitTiming.medianFilter        = IfxAsclin_SamplesPerBit_three;
    ascConfig.bitTiming.samplePointPosition = IfxAsclin_SamplePointPosition_8;

    /* ISR priorities and interrupt target */
    ascConfig.interrupt.rxPriority    = UART_INT_PRIO_RX;


    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins = {
        NULL_PTR, IfxPort_InputMode_pullUp,                                     /* CTS pin not used                  */
        SERIALIO.rx_pin, IfxPort_InputMode_pullUp,                              /* RX pin                            */
        NULL_PTR, IfxPort_OutputMode_pushPull,                                  /* RTS pin not used                  */
        SERIALIO.tx_pin, IfxPort_OutputMode_pushPull,                           /* TX pin                            */
        IfxPort_PadDriver_cmosAutomotiveSpeed1};
    ascConfig.pins = &pins;

    /* Initialize module with above parameters */
    IfxAsclin_Asc_initModule(&ascHandle, &ascConfig);

    /* Set the Transmit FIFO Level Flag (TFL) via the FLAGSSET register to start the transmission */
    SERIALIO.asclin->FLAGSSET.B.TFLS = 1;
}

#ifdef __TASKING__

/* Retarget for Tasking compiler */
void _io_putc (char character)
{
    while (IfxAsclin_getTxFifoFillLevelFlagStatus(SERIALIO.asclin) != TRUE)
    {}

    IfxAsclin_clearTxFifoFillLevelFlag(SERIALIO.asclin);

    /* Send the character */
    IfxAsclin_writeTxData(SERIALIO.asclin, character);
}

#endif /* __TASKING__ */






/*********************************************************************************************************************/
/*                                                       Timer                                                       */
/*********************************************************************************************************************/

#define ISR_PRIORITY_ATOM   1                        /* Interrupt priority number                                    */
#define ATOM_FREQ           2.0f                     /* ATOM frequency                                               */
#define CMU_FREQ            1000000.0f               /* CMU clock frequency                                          */
#define LED                 &MODULE_P03, 9           /* LED which will be toggled in Interrupt Service Routine (ISR) */


IfxEgtm_Atom_Timer           g_timerDriver;          /* ATOM driver                                                  */
static uint8               wait_time = 0;


/* This function initializes the ATOM */
void Init_Timer(void)
{
    IfxEgtm_enable(&MODULE_EGTM);                                                /* Enable EGTM                      */

    IfxEgtm_Atom_Timer_Config timerConfig;                                       /* Timer configuration structure    */
    IfxEgtm_Atom_Timer_initConfig(&timerConfig, &MODULE_EGTM);                   /* Initialize default parameters    */

    timerConfig.cluster = IfxEgtm_Cluster_0;                                     /* Select the Cluster 0             */
    timerConfig.timerChannel = IfxEgtm_Atom_Ch_0;                                /* Select ATOM channel 0            */
    timerConfig.clock = IfxEgtm_Atom_Ch_ClkSrc_cmuclk0;                          /* Select the CMU clock 0           */
    timerConfig.frequency = ATOM_FREQ;                                           /* Set timer frequency              */
    timerConfig.interrupt.isrPriority = ISR_PRIORITY_ATOM;                       /* Set interrupt priority           */
    timerConfig.interrupt.isrProvider = IfxSrc_Tos_cpu0;                         /* Set interrupt provider           */

    IfxEgtm_Cmu_setClkFrequency(&MODULE_EGTM, IfxEgtm_Cmu_Clk_0, CMU_FREQ);      /* Set the clock frequency          */
    IfxEgtm_Cmu_enableClocks(&MODULE_EGTM, IFXEGTM_CMU_CLKEN_CLK0);              /* Enable the CMU clock 0           */
    IfxEgtm_Atom_Timer_init(&g_timerDriver, &timerConfig);                       /* Initialize the ATOM              */

    IfxPort_setPinModeOutput(LED, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);  /* Set LED pin mode      */
}

void Start_Timer(uint8 tick_count_in_sec)
{
    wait_time = tick_count_in_sec;
    IfxEgtm_Atom_Timer_run(&g_timerDriver);                                      /* Start the ATOM                   */
}


void Stop_Timer(void)
{
    IfxEgtm_Atom_Timer_stop(&g_timerDriver);                                      /* Stop the ATOM                   */
}

/* Macro to define the Interrupt Service Routine */
IFX_INTERRUPT(interruptHandlerEgtmAtom, 0, ISR_PRIORITY_ATOM);

/* Interrupt Service Routine of the ATOM */
void interruptHandlerEgtmAtom(void)
{

    IfxPort_togglePin(LED);                                                      /* Toggle the LED                   */
    IfxEgtm_Atom_Timer_acknowledgeTimerIrq(&g_timerDriver);                      /* Reset the timer event            */

    static uint8 period_time = 0;

    if(period_time == (wait_time/2))
    {
        printf("ins:Time Period is going to expire\n");
        printf("ins: Please complete the test soon\n");
    }
    else if(period_time == wait_time)
    {
        Stop_Timer();
        period_time = 0;
        wait_time = 0;
        printf("ins: Test Time period expired\n");
    }

    period_time++;

}






