/**********************************************************************************************************************
 * \file EGTM_ATOM_Interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxPort.h"
#include "IfxEgtm_Atom_Timer.h"
#include <stdint.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_ATOM   1                        /* Interrupt priority number                                    */
#define ATOM_FREQ           2.0f                     /* ATOM frequency                                               */
#define CMU_FREQ            1000000.0f               /* CMU clock frequency                                          */
#define LED                 &MODULE_P03, 9           /* LED which will be toggled in Interrupt Service Routine (ISR) */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxEgtm_Atom_Timer           g_timerDriver;          /* ATOM driver                                                  */

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/


/* This function initializes the ATOM */
void Init_Timer(void)
{
    IfxEgtm_enable(&MODULE_EGTM);                                                /* Enable EGTM                      */

    IfxEgtm_Atom_Timer_Config timerConfig;                                       /* Timer configuration structure    */
    IfxEgtm_Atom_Timer_initConfig(&timerConfig, &MODULE_EGTM);                   /* Initialize default parameters    */

    timerConfig.cluster = IfxEgtm_Cluster_0;                                     /* Select the Cluster 0             */
    timerConfig.timerChannel = IfxEgtm_Atom_Ch_0;                                /* Select ATOM channel 0            */
    timerConfig.clock = IfxEgtm_Atom_Ch_ClkSrc_cmuclk0;                          /* Select the CMU clock 0           */
    timerConfig.frequency = ATOM_FREQ;                                           /* Set timer frequency              */
    timerConfig.interrupt.isrPriority = ISR_PRIORITY_ATOM;                       /* Set interrupt priority           */
    timerConfig.interrupt.isrProvider = IfxSrc_Tos_cpu0;                         /* Set interrupt provider           */

    IfxEgtm_Cmu_setClkFrequency(&MODULE_EGTM, IfxEgtm_Cmu_Clk_0, CMU_FREQ);      /* Set the clock frequency          */
    IfxEgtm_Cmu_enableClocks(&MODULE_EGTM, IFXEGTM_CMU_CLKEN_CLK0);              /* Enable the CMU clock 0           */
    IfxEgtm_Atom_Timer_init(&g_timerDriver, &timerConfig);                       /* Initialize the ATOM              */

    IfxPort_setPinModeOutput(LED, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);  /* Set LED pin mode      */
}

void Start_Timer(void)
{
    IfxEgtm_Atom_Timer_run(&g_timerDriver);                                      /* Start the ATOM                   */
}


void Stop_Timer(void)
{
    IfxEgtm_Atom_Timer_stop(&g_timerDriver);                                      /* Stop the ATOM                   */
}

/* Macro to define the Interrupt Service Routine */
IFX_INTERRUPT(interruptHandlerEgtmAtom, 0, ISR_PRIORITY_ATOM);

/* Interrupt Service Routine of the ATOM */
void interruptHandlerEgtmAtom(void)
{
    static uint8 count = 0;
    count++;
    IfxEgtm_Atom_Timer_acknowledgeTimerIrq(&g_timerDriver);                      /* Reset the timer event            */
    IfxPort_togglePin(LED);                                                      /* Toggle the LED                   */

    if(count == 10)
    {
        Stop_Timer();
        count = 0;
    }
}


